# fly.toml app configuration file for gap-down-stocks with working cron setup via Supercronic

app = 'gap-down-stocks'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

# Declare processes
[processes]
  app = "python gap_down_email.py"
  cron = "supercronic /app/crontab"

[[services]]
  internal_port = 8000
  processes = ["app"]
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
